### ISSUE TITLE
Nueva relación entre Venta y Cliente

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_lh_p3_g1_sf#20]
**Descripción:** Agregar una relación `@ManyToOne` en la entidad `Venta` para que cada venta esté asociada a un cliente.

**Pasos:** 

1. En la entidad `Venta`, agregar un atributo `Cliente cliente`.
2. Anotar el nuevo atributo con `@ManyToOne`.

**Evidencia:** Adjuntar una captura de pantalla del diagrama de base de datos en el pull request.

**Nota:** No añadir los archivos al commit con `git add .`.

**Comment by MartinEmmSuarez** [comment]
![relacion venta clientes](https://github.com/ahumadamob/2024_lh_p3_g1_sf/assets/141088623/5fe9c12e-c0f0-4544-9a2a-7cbf5a255e47)
